application: othaeventline
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on
- appstats: on

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static/css
  static_dir: static/css

- url: /.*
  script: web.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^lib/.*
- ^static/src/.*
- ^static/dst/.*